### ISSUE TITLE
"Speaking" URL for address detail pages

### ISSUE THREAD

**Issue by fredericalpers** [onOfficeGmbH/oo-wp-plugin#925]
# "Speaking" URL for address detail pages

### Introduction
Currently, the URLs of the address detail pages only contain the data record number (e.g. www.examplewebsite.de/123/). This means that the URLs are not very meaningful and not particularly user-friendly.

### User Story
As a real estate agent, I would like to have the ability to enable "speaking" URLs for the address detail pages that use the contact's first name, last name and company if these fields are filled in.

To improve the user experience and make the URLs easier to understand for both users and search engines, I would like to have the option of activating a speaking URL similar to properties. The URL of the address details page should be generated based on the first name, last name and company fields, provided these fields are filled. The URL should support the following formats e.g.:

www.examplewebsite.de/123/max-mustermann/ (first name + last name)
www.examplewebsite.de/123/max-mustermann-onoffice/ (first name + last name + company)
www.examplewebsite.de/123/onoffice/ (Company only)

### Task/Requirements
- [x] The real estate agent can decide in the plugin settings whether to activate the "speaking" URL.
- [x] If neither first name, surname nor company are filled in, the URL remains the old, record-based version (e.g. www.examplewebsite.de/123/).
- [x] All input values (first name, surname, company) must be checked for special characters or invalid characters (e.g. spaces, umlauts, etc.) that could potentially lead to problems in the URL.
- [x] If the first name or surname contains special characters such as spaces, these are encoded correctly in the URL (e.g. spaces are replaced by hyphens).
- [x] The old URLs (data record numbers) should continue to work, even if the speaking URL is activated.
- [x] Unnecessary redirects in multilingual setup must be avoided.

**Comment by dai-eastgate** [comment]
@fredericalpers I would like to confirm some points with you:

> The URL of the address details page should be generated based on the first name, last name and company fields, provided these fields are filled.

1. I noticed that the first name, last name, and company fields are in two different positions, as shown in the attached image. Please let me know which field you want to add to the URL.
![image](https://github.com/user-attachments/assets/4a1a8761-04a9-4973-b45f-08dc73cb28d6)



> * The real estate agent can decide in the plugin settings whether to activate the "speaking" URL.

2. We will create a checkbox in the plugin settings to be able to switch between the 2 URL formats:
Old URL: url/id
"Speaking" URL: url/id/name-company
Do I understand this correctly?
![image](https://github.com/user-attachments/assets/ed77c715-2383-468d-a65e-072eeda16ab3)




> * The old URLs (data record numbers) should continue to work, even if the speaking URL is activated.

3. If the "Speaking" URL is enabled, and the URL is: url/1397811/le-linh-abcd/, 
then even if you only enter the URL: url/1397811/, 
he website will still load correctly and will not be redirected to url/1397811/le-linh-abcd/. 
Is this correct?

**Comment by fredericalpers** [comment]
>1. I noticed that the first name, last name, and company fields are in two different positions, as shown in the attached image. Please let me know which field you want to add to the URL.

I'm afraid I'm not 100% sure, what exactly you mean.

![name-company3](https://github.com/user-attachments/assets/6e66e247-13ed-47b4-b777-abbdb3ba15b3)


>2. We will create a checkbox in the plugin settings to be able to switch between the 2 URL formats:
Old URL: url/id
"Speaking" URL: url/id/name-company
Do I understand this correctly?

Exactly. The feature is intended as it is for the property detail page.

>3. If the "Speaking" URL is enabled, and the URL is: url/1397811/le-linh-company/,
then even if you only enter the URL: url/1397811/,
he website will still load correctly and will not be redirected to url/1397811/le-linh-company/.
Is this correct?

The feature should be as it is with property detail pages and "speaking" URLs. Which means If I activated the feature and use the url/123/ it will redirect to url/123-name-company/

**Comment by dai-eastgate** [comment]
@fredericalpers Please take a look at my demo video and let me know your opinions. Thanks!

https://github.com/user-attachments/assets/d2580c7e-4efa-4d20-bd5f-95cfc23a9f77

Note: I am currently filling in the full first name, last name, and company on the URL. Therefore, addresses with long names are still fully displayed and not truncated like in estate details.

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! I will review this as soon as possible :)
